baseURL = 'https://master.d32cbkqy3gbz0y.amplifyapp.com/'
languageCode = 'en-us'
title = 'Krutel Katering'
theme = "hugo-scroll"

[params]
    description = "I am a description, hear me roar"
    title = "Me da title"

    # Footer
    copyright = "© Krutel Katering"